### PR TITLE
Updated string.md to match new format

### PR DESCRIPTION
**Pull request by Sandeep-source**
Hey @31Sanskrati,

Can you review this PR?

**Changes** - Removed topic column from string.md and divided according to the difficulty level.

#24

### CODE REVIEW

**Review by 31Sanskrati — CHANGES_REQUESTED** [review]
Please remove the first column as well, i.e. the column with the heading "#".  That will also solve #23

**Comment by 31Sanskrati** [comment]
@Sandeep-source please see the array.md file for any confusion in the format of the file.  As this repo is not fully finished, so the format might be confusing. I am going to follow the exact format as Array.md

**Comment by Sandeep-source** [comment]
Hey @31Sanskrati,

Now it's look fine.

Sorry for that bad PR. That's my bad

**Review by 31Sanskrati — APPROVED** [review]
I will merge the PR

**Pull request merged**
